homework3
Frontend-Sirius-VK/2022-autumn-d.stepanov pull request #3
Opened 2022-12-06 11:21 UTC by Limonadek

2022-12-12 21:55 UTC, StealthTech requested changes
Прикрепи сюда скриншоты нового экрана, пожалуйста, а также демонстрацию работы адаптивной вёрстки на старом и новом экране

И называем PR по форме — "Домашнее задание №X"

2022-12-12 21:55 UTC, StealthTech commented on backend/server.js
>  app.get('/login', (req, res) => {
Логин не требуется, можно удалить

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/content/content.js
> +            link.href = element.url_anime + element.id;
По традиции в JavaScript используем camelCase, не snake_case

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/contents/contents.css
> +        font-size: 5vw;
Так есть шанс достичь неадекватных размеров шрифтв. Рекомендую использовать свойство clamp()

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/descriptionSite/descriptionSite.css
> +        padding-right: 2vh;
Как правило, стоит указывать padding и margin в пикселях — так больше контроля за тем, как себя ведёт страница

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/descriptionSite/descriptionSite.css
> +        color: var(---color-dark-blue);
Три дефиса

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/error/error.js
> +        // this.parent = document.createElement('div');
Закомментированный код в продакшен не должен попадать

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/error/error.js
> +}
В конце файла оставляем пустую строку: https://semakin.dev/2020/05/no_newline_at_end_of_file/

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/header/header.css
> +    /* font-size: 1.5em; */
Почистить закомментированный код

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/header/header.css
> +        height: 9vh;
Шапку лучше делать фиксированной высоты, чтобы на разных экранах не разъезжалось

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/header/header.css
> +    header {
Делаем селекторы по классу

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/loader/loader.css
> +    border: 5px solid rgb(0, 0, 0);
Цвета выносим в палитру

2022-12-12 21:55 UTC, StealthTech commented on frontend/components/pageContent/pageContent.js
> +        image.src = data[0].url_image;
Тут нигде кроме data[0] нет использования data — давай сразу передавать сюда data[0]. И свойства должны быть в camelCase

2022-12-12 21:55 UTC, StealthTech commented on frontend/model/animeContents.js
> +            case 500:  EventBus.emit('animeContents:server-error', ['Ошибка 500', 'Ошибка обращения к сервису. Попробуйте обновить страницу.']);
Эти данные (массив) можно вынести куда-нибудь в константы выше

2022-12-12 21:55 UTC, StealthTech commented on frontend/routing/Router.js
> +            const id = pathName.match(rex)[0];
Можно сразу return pathName..., const id здесь лишнее

2022-12-12 21:55 UTC, StealthTech commented on frontend/routing/Router.js
> +            console.log('404')
Логи в консоль в продакшене избегаем

2022-12-15 21:18 UTC, StealthTech commented
Нашел такой же код с такими же ошибками как у Ангелины и Димы. Напомню, что ваша задача самостоятельно разобраться — постараться сделать свой вариант, столкнуться с проблемами, задать вопросы. Просто копировать нельзя, за найденное впредь дублирование кода будем снижать баллы

2022-12-15 21:19 UTC, StealthTech requested changes
Завести локальную разработку, поправить новые комментарии.
**Дедлайн: 17.12.22 23:59**

2022-12-15 21:19 UTC, StealthTech commented on backend/server.js
> +const bodyParser = require("body-parser");
Одинарные кавычки

2022-12-15 21:19 UTC, StealthTech commented on backend/server.js
> +    res.json({deleteId});
Мы рекомендуем не возвращать тело в ответах на запрос типа DELETE

2022-12-15 21:19 UTC, StealthTech commented on backend/server.js
> +app.post('/create', async (req, res) => {
Здесь и ниже требуется поддержать REST, нельзя просто /create, /update и прочее — для этого есть типы запросов

2022-12-15 21:19 UTC, StealthTech commented on backend/server.js
> +    const { id, urlImage, urlAnime, nameAnime, categoryAnime, ageAnime, descriptionAnime } = req.body;
Нет проверки, что всё это есть в req.body — может быть исключение при работе с базой

2022-12-15 21:19 UTC, StealthTech commented on frontend/components/content/content.js
> +import EventBus from "../../utils/eventBus.js";
Одинарные кавычки

2022-12-15 21:19 UTC, StealthTech commented on frontend/components/content/content.css
> +        background-color: var(--color-white-smoke);
Названия переменных с цветами должно быть обосновано смыслом, а не визуалом. Например, завтра мы захотим сделать тёмную тему на сайте. Этот background-color должен будет поменять цвет, и станет уже не white-smoke, а название переменной останется то же. Давай переименуем, чтобы оно подходило по смыслу к использованию

2022-12-15 21:19 UTC, StealthTech commented on frontend/components/content/content.css
> +        width: clamp(23vh, 25vh, 27vh);
Резиновая вёрстка — хорошо, но задание было сделать адаптивную. Давай добавим сюда медиа-выражений на размеры экранов. И ты уверен, что привязывать ширину к высоте — правильно?

2022-12-15 21:19 UTC, StealthTech commented on frontend/components/descriptionSite/descriptionSite.css
> +
Лишняя пустая строка

2022-12-15 21:19 UTC, StealthTech commented on frontend/components/content/content.css
> +        font-size: clamp(3vh, 3.5vh, 4vh);
Для шрифтов надёжнее меньшую и большую границы ставить в пикселях

2022-12-15 21:19 UTC, StealthTech commented on frontend/components/error/error.js
> +}
Не исправлено

2022-12-15 21:19 UTC, StealthTech commented on frontend/components/header/header.css
> +    header {
Не исправлено

2022-12-15 21:19 UTC, StealthTech commented on frontend/model/animeContents.js
> +    constructor(id = null, urlimage = null, urlanime = null, nameanime = null, categoryanime = null, ageanime = null, descriptionanime = null) {
Тут можно сделать деструктуризацию, чтобы немного упростить сигнатуру

2022-12-15 21:19 UTC, StealthTech commented on frontend/model/animeContents.js
> +            EventBus.emit('animeContents:got-by-id-info', this.pareserData(data)[0]);
pareser?

2022-12-15 21:19 UTC, StealthTech commented on frontend/model/animeContents.js
> +        return data.map(element => {
Место для деструктуризации — можно через ({id, urlimage: urlImage, urlanime: urlAnime, ...})
Почему, кстати, в одном месте с маленькой, в другом с большой?

2022-12-15 21:19 UTC, StealthTech commented on frontend/model/animeContents.js
> +            const anime = new AnimeContents();
И почему не использовать просто конструктор?

2022-12-15 21:19 UTC, StealthTech commented on frontend/routing/Router.js
> +        controller: ContentController
Надо бы внести какую-то общую конвенцию — у тебя в разных местах связанные вещи называются Anime, AnimeContents, ContentController, pageContent — давай один вариант какой-нибудь. Типа Anime, AnimeController, AnimePage

2022-12-15 21:19 UTC, StealthTech commented on frontend/routing/Router.js
> +    getId() {
Функция не нужна —  ID можно получить с помощью того же регулярного выражения в функции invokeController

2022-12-15 21:19 UTC, StealthTech commented on frontend/routing/Router.js
> +            return true;
Можно заменить на return Boolean(matches) или return !!matches

2022-12-15 21:19 UTC, StealthTech commented on frontend/routing/Router.js
> +        controller.process(id);
Не всем контроллерам нужен id, давай передавать по необходимости

2022-12-15 21:19 UTC, StealthTech commented on frontend/routing/Router.js
> -    stop() {
Почему удалил stop?

2022-12-15 21:19 UTC, StealthTech commented on frontend/routing/Router.js
> -        document.addEventListener('click', this.onDocumentClick);
Почему удалил обработку кликов?

2022-12-15 21:19 UTC, StealthTech commented on frontend/model/animeContents.js
> +        fetch('/contents').then((response) => {
Лучше вызовы бекенда делать сразу с префиксом /api, иначе будут проблемы с проксированием в webpack

2022-12-15 21:19 UTC, StealthTech commented on frontend/components/error/error.js
> +        errorStatus.textContent = data[0];
Можно поймать ошибку или undefined

2022-12-15 21:19 UTC, StealthTech commented on frontend/model/animeContents.js
> +            case 404: EventBus.emit('animeContents:not-found', NOT_FOUND);
Можно обойтись одним событием на все типы ошибок

2022-12-15 21:19 UTC, StealthTech commented on frontend/model/animeContents.js
> +const NOT_FOUND = ['Ошибка 404', 'Страница, которую вы запрашиваете, не существует. Возможно был введен неверный адрес.'];
Лучше объект. title и description

2022-12-15 21:21 UTC, Limonadek commented on frontend/model/animeContents.js
> +        fetch('/contents').then((response) => {
на 4 ветке уже сделал

2022-12-16 14:50 UTC, Limonadek commented on frontend/model/animeContents.js
> +        return data.map(element => {
берутся переменные с бд, а в бд не используют большие буквы, так как sql их всех в нижний регистр ставит

2022-12-18 13:56 UTC, StealthTech requested changes
**Дедлайн:** 19.12.22 23:59
Нужны исправления.

2022-12-18 13:56 UTC, StealthTech commented on frontend/routing/Router.js
> +    run() {
Не понимаю, зачем метод run, когда уже есть start? Не навешивается обработчик на клики по ссылкам — приложение не работает как SPA. Каждый раз с сервера перезапрашивается index.html, когда переходишь по ссылке на сайте

2022-12-18 13:56 UTC, StealthTech commented on backend/server.js
> +app.post('/', async (req, res) => {
По rest в url должно быть название сущности, не просто слеш

2022-12-18 13:56 UTC, StealthTech commented on frontend/components/contents/contents.css
> +    .contents__style {
Неудачно названы компоненты — пересекается .content и .contents. Ты даже сам их путаешь, видимо

<img width="488" alt="image" src="https://user-images.githubusercontent.com/5190765/208301921-b15df663-987e-4f2e-b85c-ee5480ff490a.png">

2022-12-18 13:56 UTC, StealthTech commented on frontend/components/contents/contents.css
> +    .contents__style {
<img width="302" alt="image" src="https://user-images.githubusercontent.com/5190765/208301934-0761e94b-6a42-446c-bd15-f67812fb2678.png">

2022-12-18 13:56 UTC, StealthTech commented on frontend/index.js
> +router.run();
Стоит вернуть как было

2022-12-18 17:19 UTC, StealthTech approved these changes
ДЗ №3 принято

2022-12-18 17:19 UTC, merged