Домашняя работа №4
Frontend-Sirius-VK/2022-autumn-d.stepanov pull request #4
Opened 2022-12-14 15:17 UTC by Limonadek

2022-12-18 20:11 UTC, Limonadek commented
апи адресс http://87.239.109.131
конфиг nginx
![Снимок экрана от 2022-12-18 23-09-56](https://user-images.githubusercontent.com/91593149/208317210-dce96fd4-ad85-461b-8356-d3f196306ce7.png)

2022-12-20 20:48 UTC, Betchika99 requested changes
- [ ] из кода убираем комментарии и логи
- [ ] сейчас в сборку фронтенда попадают картинки для постов, которые по логике должны не на фронте быть, а на бекенде (и приходит в апи сервера как урл для картинки). нужно починить это в сборке
- [ ] логика БЭМ не особо осознанна. делать элементами "h2" и прочие теги - это читерство. нужно перечитать документацию и вникнуть в смысл

рекомендации к защите:
![image](https://user-images.githubusercontent.com/34346716/208758673-07fff52f-6ce3-460a-a206-7e29c70b096f.png)
1 - убрать некликабельные или ведущие вникуда кликабельные элементы (или задизайблить их)
2 - добавить немного "воздуха" внизу, а то последняя картинка максимально прибита к нижней границе экрана. обычно для воздуха используют футер, чтобы оставить там какие-то контакты. этого можно не делать, достаточно просто добавить нижний отступ

2022-12-20 20:48 UTC, Betchika99 commented on backend/server.js
> +app.get('/api/animeContents', async (req, res) => {
было корректнее. оставь /api/contents здесь и далее. соответствуем REST

2022-12-20 20:48 UTC, Betchika99 commented on backend/server.js
> +// });
комменты стираем

2022-12-20 20:48 UTC, Betchika99 commented on backend/server.js
> +app.use(express.static('dist'));
ненужная настройка

2022-12-20 20:48 UTC, Betchika99 commented on frontend/components/content/content.js
> +}
не очень понятно, зачем эта функция. тебе картинки сразу приходят с сервера (вернее, урлы на них). их можно сразу передавать в шаблон, а там вставлять в img.src

2022-12-20 20:48 UTC, Betchika99 commented on frontend/components/content/content.js
> +            const context = {newUrlImage, urlAnime, id, nameAnime, categoryAnime, ageAnime, descriptionAnime};
избыточная переменная, можно сразу в шаблон передавать объект

2022-12-20 20:48 UTC, Betchika99 commented on frontend/components/contentContainer/contentContainer.css
> +.contents-heading__h2{
не очень понятная логика БЭМ здесь. скорее .contents__heading получается. или как ты хотел?

2022-12-20 20:48 UTC, Betchika99 commented on frontend/components/contentContainer/contentContainer.js
> +        this.content = new Content(document.querySelector('.contents'), this.contentsPost);
если на странице нет элемента с селектором '.contents', будет исключение. лучше сначала получить ноду по селектору, проверить ее. а уже потом передавать в конструктор, если всё хорошо

2022-12-20 20:48 UTC, Betchika99 commented on frontend/components/header/header.js
> +import AnimegoLogo from '../../../backend/image/logo/logo.png';
почему лого лежит в папке бекенда? перенеси на фронтенд и пусть лежит с основной статикой

2022-12-20 20:48 UTC, Betchika99 commented on frontend/index.html
> +        <!-- <link href="/frontend/main.css" rel="stylesheet"> -->
убираем комменты

2022-12-20 20:48 UTC, Betchika99 commented on package.json
> +    "build:dev": "webpack --mode development",
ненужная команда, у тебя аналогичная штука, но с удобным сервером, сделана строкой выше

2022-12-20 20:48 UTC, Betchika99 commented on package.json
> +    "compile": "handlebars ./frontend/components/descriptionSite/descriptionSite.handlebars -f ./frontend/components/descriptionSite/descriptionSite.precompiled.js"
не нужно компилировать шаблоны теперь. они компилируются вебпаком. команда лишняя

2022-12-20 20:48 UTC, Betchika99 commented on backend/migrations/V1.1.2__inser_data.sql
> +	values ('NejnyUkus.jpg', 'http://87.239.109.131/anime/', 'Нежный укус+', 'ТВ Сериал', 2012, 'В отличие от истории, искусству знакомо сослагательное наклонение. Ответ на вопрос: «Что было бы, если?»
с картинками раньше было лучше. обычно в базе хранят либо относительные урлы за картинками, либо абсолютные (прямо с хостом). подумай, как у тебя будет лучше

2022-12-20 20:48 UTC, Betchika99 commented on backend/server.js
> +    if (Object.keys(req.body).length != 10) {
так себе проверка. может я тебе туда в тело подсуну каких-то мусорных полей, чтобы число сходилось. здесь и далее

2022-12-20 20:50 UTC, Limonadek commented on backend/server.js
> +app.get('/api/animeContents', async (req, res) => {
миша сказал назвать как сущность. Поэтому переименовал. Кому верить?

2022-12-20 22:54 UTC, StealthTech commented on backend/server.js
> +app.get('/api/animeContents', async (req, res) => {
Ключевое, что я хотел донести — когда делаем API, проектируем все пути единообразно, не вразнобой. Если по REST правильнее contents, то нужно сделать все пути contents. Верить Лизе

2022-12-21 10:52 UTC, Limonadek commented on backend/server.js
> +app.get('/api/animeContents', async (req, res) => {
Миша попросил переименовать их так, как называется сущность.Мне такой вариант кажется более правильным. Может все таки оставить?

2022-12-21 23:29 UTC, Betchika99 approved these changes

2022-12-22 20:34 UTC, merged